### ISSUE TITLE
Get TimeoutException if in certain network

### ISSUE THREAD

**Issue by pakaufmann** [koush/AndroidAsync#117]
We have a serious problem with Ion and AndroidAsync.

If our client connects the app in a certain network, no call with ION will ever connect successfully. All we get is a TimeoutException while trying to connect to the URL.

Output with LogLevel Verbose:

03-10 11:10:23.444  14945-14985/? D/GOOGLEREQUEST﹕ (0 ms) http://www.google.ch: Executing request.
03-10 11:10:23.454  14945-14985/? D/GOOGLEREQUEST﹕ (18 ms) http://www.google.ch: Connecting socket
03-10 11:10:26.457  14945-14985/? E/GOOGLEREQUEST﹕ (3010 ms) http://www.google.ch: Connection error
03-10 11:10:26.467  14945-14985/? E/GOOGLEREQUEST﹕ null
    java.util.concurrent.TimeoutException
            at com.koushikdutta.async.http.AsyncHttpClient$2.run(AsyncHttpClient.java:184)
            at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:665)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:676)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:583)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:36)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:531)

The interesting thing is, if we make the same call to the same URL with a simple DefaultHttpClient of the android core API it works every time.

Is there a workaround for this, as I'm not really keen on changing all my API calls to work with the DefaultHttpClient instead of ION.

**Comment by vineetv2821993** [comment]
Hi Everyone, Is this issue resolved and fixed in main library? i am trying to make web socket connection to ws://echo.websocket.org (http://www.websocket.org/echo.html)

I am getting error : 10-12 06:53:31.198  29835-30026/naxap.widgettest W/System.err﹕ java.util.concurrent.TimeoutException
W/System.err﹕ at com.koushikdutta.async.http.AsyncHttpClient$2.run(AsyncHttpClient.java:247)
W/System.err﹕ at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:709)
W/System.err﹕ at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:726)
W/System.err﹕ at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:627)
W/System.err﹕ at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
W/System.err﹕ at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:569)

I wrote this code in OnClick of a button :-1: 
                AsyncHttpClient.getDefaultInstance().websocket("ws://echo.websocket.org", "ws", new AsyncHttpClient.WebSocketConnectCallback() {
                    @Override
                    public void onCompleted(Exception ex, WebSocket webSocket) {
                        if (ex != null) {
                            ex.printStackTrace();
                            Log.d("WebSocket", "Failed");
                            return;
                        }
                        webSocket.send("Socket Test");
                        webSocket.send(new byte[10]);
                        webSocket.setStringCallback(new WebSocket.StringCallback() {
                            public void onStringAvailable(String s) {
                                Log.d("WebSocket", "I got a string: " + s);
                            }
                        });
                        webSocket.setDataCallback(new DataCallback() {
                            public void onDataAvailable(DataEmitter emitter, ByteBufferList byteBufferList) {
                                Log.d("WebSocket", "I got some bytes!");
                                // note that this data has been read
                                byteBufferList.recycle();
                            }
                        });
                    }
                });
