### ISSUE TITLE
Handle lost connection more gracefully

### ISSUE THREAD

**Issue by konradreiche** [koush/AndroidAsync#164]
I am using the websocket client of AndroidAsync. It works nicely, except when the network connection is lost I am getting a `java.net.SocketException` which I don't know how to handle gracefully.

Basically, I do not see any options here except offer a proper callback handler. The callback handler which is set through `setEndCallback` is invoked, but it will not circumvent the exception thrown in the background.

Stacktrace:

```
E/NIO﹕ Unhandled exception
    java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)
            at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:552)
            at libcore.io.IoBridge.recvfrom(IoBridge.java:528)
            at java.nio.SocketChannelImpl.readImpl(SocketChannelImpl.java:305)
            at java.nio.SocketChannelImpl.read(SocketChannelImpl.java:267)
            at com.koushikdutta.async.SocketChannelWrapper.read(SocketChannelWrapper.java:24)
            at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:157)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:755)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:600)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:37)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:549)
     Caused by: libcore.io.ErrnoException: recvfrom failed: ETIMEDOUT (Connection timed out)
            at libcore.io.Posix.recvfromBytes(Native Method)
            at libcore.io.Posix.recvfrom(Posix.java:126)
            at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:159)
            at libcore.io.IoBridge.recvfrom(IoBridge.java:525)
            at java.nio.SocketChannelImpl.readImpl(SocketChannelImpl.java:305)
            at java.nio.SocketChannelImpl.read(SocketChannelImpl.java:267)
            at com.koushikdutta.async.SocketChannelWrapper.read(SocketChannelWrapper.java:24)
            at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:157)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:755)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:600)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:37)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:549)
```

**Comment by fadeaway** [comment]
Was this ever fixed? I'm having the same issue I implemented the callback below but it never fires. I just get the error logged out.

                    webSocket.setEndCallback(new CompletedCallback() {
                        @Override
                        public void onCompleted(Exception e) {
                            Log.i(TAG, "setEndCallback called.");
                        }
                    });

**Comment by mnomansadiq** [comment]
any update on this have a same problem that setEndCallback not working if wifi disconnect etc ?
