### ISSUE TITLE
Socket.io NPE

### ISSUE THREAD

**Issue by g00fy-** [koush/AndroidAsync#165]
It looks like there is an NPE. 

`````` java
E/NIO﹕ Unhandled exception
    java.lang.NullPointerException
            at com.koushikdutta.async.http.socketio.SocketIOConnection$13.onStringAvailable(SocketIOConnection.java:427)
            at com.koushikdutta.async.http.socketio.transport.WebSocketTransport$1.onStringAvailable(WebSocketTransport.java:54)
            at com.koushikdutta.async.http.WebSocketImpl$1.onMessage(WebSocketImpl.java:89)
            at com.koushikdutta.async.http.HybiParser.emitFrame(HybiParser.java:420)
            at com.koushikdutta.async.http.HybiParser.access$800(HybiParser.java:46)
            at com.koushikdutta.async.http.HybiParser$5.onDataAvailable(HybiParser.java:197)
            at com.koushikdutta.async.DataEmitterReader.handlePendingData(DataEmitterReader.java:24)
            at com.koushikdutta.async.DataEmitterReader.onDataAvailable(DataEmitterReader.java:41)
            at com.koushikdutta.async.Util.emitAllData(Util.java:20)
            at com.koushikdutta.async.AsyncSSLSocketWrapper$2.onDataAvailable(AsyncSSLSocketWrapper.java:124)
            at com.koushikdutta.async.BufferedDataEmitter.onDataAvailable(BufferedDataEmitter.java:33)
            at com.koushikdutta.async.BufferedDataEmitter.onDataAvailable(BufferedDataEmitter.java:61)
            at com.koushikdutta.async.Util.emitAllData(Util.java:20)
            at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:175)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:755)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:600)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:37)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:549)```
``````

**Comment by bhoomika0804** [comment]
I am getting this issue  when I restart server. How to solve this? I want socket connection for v0.9
