### ISSUE TITLE
NPE in SocketIOConnection

### ISSUE THREAD

**Issue by fiskbil** [koush/AndroidAsync#184]
Running AndroidAsync 1.2.6. I have not been able to reproduce this myself but we are getting these crash reports from out in the wild.

```
java.lang.NullPointerException
       at com.koushikdutta.async.http.socketio.SocketIOConnection$3.run(SocketIOConnection.java:178)
       at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:675)
       at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:692)
       at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:600)
       at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:37)
       at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:549)
```

Since our app is not on the stack it's difficult to track down what's causing this, but I suspect it is during socket disconnect. 
It happens on a wide range of devices, android versions and manufacturers.

**Comment by kharvd** [comment]
Same problem

**Comment by siga111** [comment]
Version 1.4.1, problem still there, some lines numbers are different
```
java.lang.NullPointerException
       at com.koushikdutta.async.http.socketio.SocketIOConnection$3.run(SocketIOConnection.java:178)
       at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:683)
       at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:700)
       at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:608)
       at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:37)
       at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:557)
```

**Comment by qbig** [comment]
java.lang.NullPointerException
       at com.koushikdutta.async.http.socketio.SocketIOConnection$3.run(SocketIOConnection.java:180)
       at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:708)
       at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:725)
       at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
       at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
       at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)

**Comment by fiskbil** [comment]
Closing due to inactivity.
