### ISSUE TITLE
L: SSL certificate issues

### ISSUE THREAD

**Issue by venuatu** [koush/AndroidAsync#187]
I'm having some issues connecting to a backend HTTPS service in an app on android L.

There is an [issue on the L bugtracker](https://code.google.com/p/android-developer-preview/issues/detail?id=328&q=ssl&colspec=ID%20Type%20Status%20Owner%20Summary) that may be related to this (though it uses jetty)

I reproduced this with new project in android studio using `com.koushikdutta.ion:ion:1.2.7` with:

``` java
Ion.getDefault(this).configure().setLogging("iontest", Log.VERBOSE);
Ion.with(this).load("https://www.google.com/").asString().then(new FutureCallback<String>() {
    @Override
    public void onCompleted(Exception e, String result) {
        ((TextView)findViewById(R.id.text_view)).setText(e != null ? e.toString() : result);
    }
});
```

Nexus 7:

```
V/iontest (  486): (87 ms) https://www.google.com/: socket connected
V/iontest (  486): (97 ms) https://www.google.com/:
V/iontest (  486): GET / HTTP/1.1
V/iontest (  486): Host: www.google.com
V/iontest (  486): User-Agent: Dalvik/2.0.0 (Linux; U; Android L Build/LPV79)
V/iontest (  486): Accept-Encoding: gzip, deflate
V/iontest (  486): Connection: keep-alive
V/iontest (  486): Accept: */*
V/iontest (  486):
E/iontest (  486): (110 ms) https://www.google.com/: exception during response
E/iontest (  486): connection closed before response completed.
E/iontest (  486): com.koushikdutta.async.http.ConnectionClosedException: connection closed before response completed.
E/iontest (  486):  at com.koushikdutta.async.http.AsyncHttpResponseImpl$3.onCompleted(AsyncHttpResponseImpl.java:95)
E/iontest (  486):  at com.koushikdutta.async.AsyncSSLSocketWrapper.report(AsyncSSLSocketWrapper.java:394)
E/iontest (  486):  at com.koushikdutta.async.AsyncSSLSocketWrapper.handleResult(AsyncSSLSocketWrapper.java:253)
E/iontest (  486):  at com.koushikdutta.async.AsyncSSLSocketWrapper.write(AsyncSSLSocketWrapper.java:368)
E/iontest (  486):  at com.koushikdutta.async.Util$7.onWriteable(Util.java:192)
E/iontest (  486):  at com.koushikdutta.async.Util.writeAll(Util.java:199)
E/iontest (  486):  at com.koushikdutta.async.Util.writeAll(Util.java:207)
E/iontest (  486):  at com.koushikdutta.async.http.AsyncHttpResponseImpl.setSocket(AsyncHttpResponseImpl.java:66)
E/iontest (  486):  at com.koushikdutta.async.http.AsyncHttpClient$3.onConnectCompleted(AsyncHttpClient.java:370)
E/iontest (  486):  at com.koushikdutta.async.http.AsyncSocketMiddleware$1$2$1.onConnectCompleted(AsyncSocketMiddleware.java:244)
E/iontest (  486):  at com.koushikdutta.async.http.AsyncSSLSocketMiddleware$1.onConnectCompleted(AsyncSSLSocketMiddleware.java:52)
E/iontest (  486):  at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:783)
E/iontest (  486):  at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:600)
E/iontest (  486):  at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:37)
E/iontest (  486):  at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:549)
E/iontest (  486): Caused by: com.koushikdutta.async.AsyncSSLException: Peer not trusted by any of the system trust managers.
E/iontest (  486):  at com.koushikdutta.async.AsyncSSLSocketWrapper.handleResult(AsyncSSLSocketWrapper.java:252)
E/iontest (  486):  ... 12 more
E/iontest (  486): Caused by: javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
E/iontest (  486):  at com.android.org.conscrypt.SSLNullSession.getPeerCertificates(SSLNullSession.java:104)
E/iontest (  486):  at com.koushikdutta.async.AsyncSSLSocketWrapper.handleResult(AsyncSSLSocketWrapper.java:229)
E/iontest (  486):  ... 12 more
```

arm emulator:

```
V/iontest ( 1443): (1524 ms) https://www.google.com/:
V/iontest ( 1443): GET / HTTP/1.1
V/iontest ( 1443): Host: www.google.com
V/iontest ( 1443): User-Agent: Dalvik/2.0.0 (Linux; U; Android L Build/LPV81B)
V/iontest ( 1443): Accept-Encoding: gzip, deflate
V/iontest ( 1443): Connection: keep-alive
V/iontest ( 1443): Accept: */*
V/iontest ( 1443):
E/iontest ( 1443): (1789 ms) https://www.google.com/: exception during response
E/iontest ( 1443): connection closed before response completed.
E/iontest ( 1443): com.koushikdutta.async.http.ConnectionClosedException: connection closed before response completed.
E/iontest ( 1443):  at com.koushikdutta.async.http.AsyncHttpResponseImpl$3.onCompleted(AsyncHttpResponseImpl.java:95)
E/iontest ( 1443):  at com.koushikdutta.async.AsyncSSLSocketWrapper.report(AsyncSSLSocketWrapper.java:394)
E/iontest ( 1443):  at com.koushikdutta.async.AsyncSSLSocketWrapper.handleResult(AsyncSSLSocketWrapper.java:253)
E/iontest ( 1443):  at com.koushikdutta.async.AsyncSSLSocketWrapper.write(AsyncSSLSocketWrapper.java:368)
E/iontest ( 1443):  at com.koushikdutta.async.Util$7.onWriteable(Util.java:192)
E/iontest ( 1443):  at com.koushikdutta.async.Util.writeAll(Util.java:199)
E/iontest ( 1443):  at com.koushikdutta.async.Util.writeAll(Util.java:207)
E/iontest ( 1443):  at com.koushikdutta.async.http.AsyncHttpResponseImpl.setSocket(AsyncHttpResponseImpl.java:66)
E/iontest ( 1443):  at com.koushikdutta.async.http.AsyncHttpClient$3.onConnectCompleted(AsyncHttpClient.java:370)
E/iontest ( 1443):  at com.koushikdutta.async.http.AsyncSocketMiddleware$1$2$1.onConnectCompleted(AsyncSocketMiddleware.java:244)
E/iontest ( 1443):  at com.koushikdutta.async.http.AsyncSSLSocketMiddleware$1.onConnectCompleted(AsyncSSLSocketMiddleware.java:52)
E/iontest ( 1443):  at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:783)
E/iontest ( 1443):  at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:600)
E/iontest ( 1443):  at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:37)
E/iontest ( 1443):  at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:549)
E/iontest ( 1443): Caused by: com.koushikdutta.async.AsyncSSLException: Peer not trusted by any of the system trust managers.
E/iontest ( 1443):  at com.koushikdutta.async.AsyncSSLSocketWrapper.handleResult(AsyncSSLSocketWrapper.java:252)
E/iontest ( 1443):  ... 12 more
E/iontest ( 1443): Caused by: javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
E/iontest ( 1443):  at com.android.org.conscrypt.SSLNullSession.getPeerCertificates(SSLNullSession.java:104)
E/iontest ( 1443):  at com.koushikdutta.async.AsyncSSLSocketWrapper.handleResult(AsyncSSLSocketWrapper.java:229)
E/iontest ( 1443):  ... 12 more
```

and just for my sanity, moto x on 4.4.2:

```
V/iontest (27621): (1 ms) https://www.google.com/: socket connected
V/iontest (27621): (2 ms) https://www.google.com/:
V/iontest (27621): GET / HTTP/1.1
V/iontest (27621): Host: www.google.com
V/iontest (27621): User-Agent: Dalvik/1.6.0 (Linux; U; Android 4.4.2; XT1052 Build/KLA20.16-1.38)
V/iontest (27621): Accept-Encoding: gzip, deflate
V/iontest (27621): Connection: keep-alive
V/iontest (27621): Accept: */*
V/iontest (27621):
V/iontest (27621): (3 ms) https://www.google.com/: request completed
V/iontest (27621): (39 ms) https://www.google.com/: Received headers:
V/iontest (27621): HTTP/1.1 302 Found
...
```

**Comment by helinfeng** [comment]
W/System.err: com.koushikdutta.async.AsyncSSLException: Peer not trusted by any of the system trust managers.
W/System.err:     at com.koushikdutta.async.AsyncSSLSocketWrapper.handleHandshakeStatus(AsyncSSLSocketWrapper.java:322)
W/System.err:     at com.koushikdutta.async.AsyncSSLSocketWrapper.access$000(AsyncSSLSocketWrapper.java:30)
W/System.err:     at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:213)
W/System.err:     at com.koushikdutta.async.Util.emitAllData(Util.java:23)
W/System.err:     at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
W/System.err:     at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:789)
W/System.err:     at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:627)
W/System.err:     at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
 W/System.err:     at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:569)
 W/System.err: Caused by: javax.net.ssl.SSLException: hostname in certificate didn't match: 
W/System.err:     at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:185)
W/System.err:  at org.apache.http.conn.ssl.StrictHostnameVerifier.verify(StrictHostnameVerifier.java:61)
W/System.err:  at com.koushikdutta.async.AsyncSSLSocketWrapper.handleHandshakeStatus(AsyncSSLSocketWrapper.java:302)

at android 4.4.4 is error   at android 6.0 & 5.0 is ok.
 the socket who can help me?

**Comment by ManLikeKip** [comment]
@helinfeng I am facing the same problem right now ?
did you fix it ?
if so , how did you ?
