### ISSUE TITLE
Socket.IO ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by vigbk** [koush/AndroidAsync#199]
I am using socket.io 0.9.14 on the server and the 1.2.5 android async library. I get a 
 java.lang.ArrayIndexOutOfBoundsException: length=1; index=1 exception when I try to connect to the server. 

![screen shot 2014-07-09 at 7 51 03 pm](https://cloud.githubusercontent.com/assets/6189632/3523822/5e4f9138-075f-11e4-9e43-da73c6200fb3.png)

**Comment by dhaval0122** [comment]
http://192.168.43.112:5000/socketio/1 or http://192.168.43.112:5000

java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
at com.koushikdutta.async.http.socketio.SocketIOConnection$2.transform(SocketIOConnection.java:118)
at com.koushikdutta.async.http.socketio.SocketIOConnection$2.transform(SocketIOConnection.java:113)
at com.koushikdutta.async.future.TransformFuture.onCompleted(TransformFuture.java:14)
at com.koushikdutta.async.future.SimpleFuture.handleCallbackUnlocked(SimpleFuture.java:107)
at com.koushikdutta.async.future.SimpleFuture.setComplete(SimpleFuture.java:141)
at com.koushikdutta.async.future.SimpleFuture.setComplete(SimpleFuture.java:128)
at com.koushikdutta.async.http.AsyncHttpClient.invokeWithAffinity(AsyncHttpClient.java:523)
at com.koushikdutta.async.http.AsyncHttpClient.access$800(AsyncHttpClient.java:51)
at com.koushikdutta.async.http.AsyncHttpClient$7.run(AsyncHttpClient.java:534)
at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:739)
at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:757)
at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:657)
at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:599)
