### ISSUE TITLE
Fatal alert received bad_record_mac

### ISSUE THREAD

**Issue by Savic** [koush/AndroidAsync#233]
Hello!

I am using AndroidAsync 1.3.8 connecting to a websocket (wss) server supporting TLSv1, TLSv1.1, TLSv1.2, SSLv3 using Android 4.4.4 on a Nexus 7 and I get the following Exception (also tried with android 4.3 and had the same issue):

08-22 11:51:32.730 5230-5361/  W/System.err﹕ javax.net.ssl.SSLException: Fatal alert received bad_record_mac
08-22 11:51:32.740 5230-5361/  W/System.err﹕ at com.android.org.conscrypt.SSLEngineImpl.unwrap(SSLEngineImpl.java:484)
08-22 11:51:32.740 5230-5361/  W/System.err﹕ at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:383)
08-22 11:51:32.740 5230-5361/  W/System.err﹕ at com.koushikdutta.async.AsyncSSLSocketWrapper$3.onDataAvailable(AsyncSSLSocketWrapper.java:261)
08-22 11:51:32.740 5230-5361/  W/System.err﹕ at com.koushikdutta.async.BufferedDataEmitter.onDataAvailable(BufferedDataEmitter.java:33)
08-22 11:51:32.740 5230-5361/  W/System.err﹕ at com.koushikdutta.async.BufferedDataEmitter.onDataAvailable(BufferedDataEmitter.java:61)
08-22 11:51:32.740 5230-5361/  W/System.err﹕ at com.koushikdutta.async.Util.emitAllData(Util.java:20)
08-22 11:51:32.740 5230-5361/  W/System.err﹕ at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:175)
08-22 11:51:32.740 5230-5361/  W/System.err﹕ at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:758)
08-22 11:51:32.740 5230-5361/  W/System.err﹕ at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:603)
08-22 11:51:32.740 5230-5361/  W/System.err﹕ at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:37)
08-22 11:51:32.740 5230-5361/  W/System.err﹕ at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:552)

The biggest problem of mine is that i cannot reproduce the error. The exception is thrown "randomly" (subjectivly spoken) while receiving data from the wesocket server. For example 1 out of 10 "fresh" connections with the server receives the exception. I would be thankful for any help!

**Comment by jznadams** [comment]
+1 for me. I can reproduce this pretty reliably in a test case. It happened occasionally in 1.8.3, but much more frequently in my test case with 2.1.3. I'm using a socket.io 0.9 server that supports only TLSv1 TLSv1.1 TLSv1.2

In my test case I connect the socket, and then send a series of calls to the same event through the socket (I'm testing our rate-limiting code).

If I do essentially this:
```
public void testRateLimit() {
    client = connectsocket(); // method to set up the socket, etc.
    sendEvent(1);
    waitForRateLimitToGetHit();
}

public void sendEvent(Integer attempt) {
    if (attempt < 30) {
        client.emit(event, data, new Acknowledge() {
                @Override
                public void acknowledge(JSONArray arguments) {
                    sendEvent(attempt + 1); // Once finished, emit again
                });
    }
}
```

With the above code, everything works fine. If I change the test to this:
```
public void testRateLimit() {
    client = connectsocket(); // method to set up the socket, etc.
    sendEvent(1);
    sendEvent(1); // start a second simultaneous loop of emits
    sendEvent(1); // and a third!
    waitForRateLimitToGetHit();
}
```

I will frequently see crashes that look like either this:

```
04-24 10:16:19.928  16468-16559/ W/System.err﹕ javax.net.ssl.SSLException: Fatal alert received bad_record_mac
04-24 10:16:19.938  16468-16559/ W/System.err﹕ at org.apache.harmony.xnet.provider.jsse.SSLEngineImpl.unwrap(SSLEngineImpl.java:485)
04-24 10:16:19.938  16468-16559/ W/System.err﹕ at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:383)
04-24 10:16:19.938  16468-16559/ W/System.err﹕ at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:191)
04-24 10:16:19.938  16468-16559/ W/System.err﹕ at com.koushikdutta.async.Util.emitAllData(Util.java:22)
04-24 10:16:19.938  16468-16559/ W/System.err﹕ at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146)
04-24 10:16:19.938  16468-16559/ W/System.err﹕ at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
04-24 10:16:19.938  16468-16559/ W/System.err﹕ at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
04-24 10:16:19.938  16468-16559/ W/System.err﹕ at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
04-24 10:16:19.948  16468-16559/ W/System.err﹕ at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
```

or this: 

```
04-24 11:10:26.716    6192-6303/ W/System.err﹕ javax.net.ssl.SSLProtocolException: Bad record MAC
04-24 11:10:26.716    6192-6303/ W/System.err﹕ at org.apache.harmony.xnet.provider.jsse.ConnectionStateTLS.decrypt(ConnectionStateTLS.java:342)
04-24 11:10:26.726    6192-6303/ W/System.err﹕ at org.apache.harmony.xnet.provider.jsse.ConnectionState.decrypt(ConnectionState.java:132)
04-24 11:10:26.726    6192-6303/ W/System.err﹕ at org.apache.harmony.xnet.provider.jsse.SSLRecordProtocol.unwrap(SSLRecordProtocol.java:382)
04-24 11:10:26.726    6192-6303/ W/System.err﹕ at org.apache.harmony.xnet.provider.jsse.SSLEngineImpl.unwrap(SSLEngineImpl.java:464)
04-24 11:10:26.736    6192-6303/ W/System.err﹕ at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:383)
04-24 11:10:26.736    6192-6303/ W/System.err﹕ at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:191)
04-24 11:10:26.736    6192-6303/ W/System.err﹕ at com.koushikdutta.async.Util.emitAllData(Util.java:22)
04-24 11:10:26.736    6192-6303/ W/System.err﹕ at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146)
04-24 11:10:26.736    6192-6303/ W/System.err﹕ at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
04-24 11:10:26.736    6192-6303/com.digium.respokesdktest W/System.err﹕ at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
04-24 11:10:26.746    6192-6303/com.digium.respokesdktest W/System.err﹕ at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
04-24 11:10:26.746    6192-6303/com.digium.respokesdktest W/System.err﹕ at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
```

If I change the test to this:


```
public void testRateLimit() {
    client = connectsocket(); // method to set up the socket, etc.
    sendEvent(1);
    sendEvent(1); // start a second simultaneous loop of emits
    sendEvent(1); // and a third!
    sendEvent(1);
    sendEvent(1); 
    sendEvent(1); // six simultaneous loops
    waitForRateLimitToGetHit();
}
```

The socket will just hang after 3 or so events are actually sent. Any ideas? I'm building an SDK other developers would use, so I don't have a whole lot of control on the sequence of calls to client.emit() without building my own queueing system on top of yours. Any ideas?
