### ISSUE TITLE
recvfrom failed: ETIMEDOUT on Android

### ISSUE THREAD

**Issue by theRaffe** [koush/AndroidAsync#270]
Hi, I got this exception after a few time. First It works ok but then it throws the exception.
I tested with 2 cellphones a Moto G and LG L7, How Can I fix this?? help!

10-30 22:19:25.837: E/NIO(15868): Unhandled exception
10-30 22:19:25.837: E/NIO(15868): java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)
10-30 22:19:25.837: E/NIO(15868):   at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:544)
10-30 22:19:25.837: E/NIO(15868):   at libcore.io.IoBridge.recvfrom(IoBridge.java:518)
10-30 22:19:25.837: E/NIO(15868):   at java.nio.SocketChannelImpl.readImpl(SocketChannelImpl.java:305)
10-30 22:19:25.837: E/NIO(15868):   at java.nio.SocketChannelImpl.read(SocketChannelImpl.java:267)
10-30 22:19:25.837: E/NIO(15868):   at com.koushikdutta.async.SocketChannelWrapper.read(SocketChannelWrapper.java:24)
10-30 22:19:25.837: E/NIO(15868):   at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:157)
10-30 22:19:25.837: E/NIO(15868):   at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:766)
10-30 22:19:25.837: E/NIO(15868):   at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:608)
10-30 22:19:25.837: E/NIO(15868):   at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:37)
10-30 22:19:25.837: E/NIO(15868):   at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:557)
10-30 22:19:25.837: E/NIO(15868): Caused by: libcore.io.ErrnoException: recvfrom failed: ETIMEDOUT (Connection timed out)
10-30 22:19:25.837: E/NIO(15868):   at libcore.io.Posix.recvfromBytes(Native Method)
10-30 22:19:25.837: E/NIO(15868):   at libcore.io.Posix.recvfrom(Posix.java:126)
10-30 22:19:25.837: E/NIO(15868):   at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:159)
10-30 22:19:25.837: E/NIO(15868):   at libcore.io.IoBridge.recvfrom(IoBridge.java:515)
10-30 22:19:25.837: E/NIO(15868):   ... 8 more

**Comment by jayrambhia** [comment]
I have got the same issue. It works well for 2-5 minutes I guess (mostly it's idle). When I try to send some data after some time, it throws this error after a while. I don't know if it's a server side problem or client side or it could be due to the long duration. I would be grateful if someone could shed some light on this issue.
