### ISSUE TITLE
Closed Selector Exception 

### ISSUE THREAD

**Issue by myrmidon-media** [koush/AndroidAsync#272]
``` log
11-02 15:47:28.123: E/NIO(8828): Selector exception
11-02 15:47:28.123: E/NIO(8828): com.koushikdutta.async.AsyncServer$AsyncSelectorException: java.nio.channels.ClosedSelectorException
11-02 15:47:28.123: E/NIO(8828):    at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:756)
11-02 15:47:28.123: E/NIO(8828):    at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
11-02 15:47:28.123: E/NIO(8828):    at com.koushikdutta.async.AsyncServer.access$4(AsyncServer.java:615)
11-02 15:47:28.123: E/NIO(8828):    at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
11-02 15:47:28.123: E/NIO(8828): Caused by: java.nio.channels.ClosedSelectorException
11-02 15:47:28.123: E/NIO(8828):    at java.nio.SelectorImpl.checkClosed(SelectorImpl.java:142)
11-02 15:47:28.123: E/NIO(8828):    at java.nio.SelectorImpl.selectInternal(SelectorImpl.java:164)
11-02 15:47:28.123: E/NIO(8828):    at java.nio.SelectorImpl.selectNow(SelectorImpl.java:160)
11-02 15:47:28.123: E/NIO(8828):    at com.koushikdutta.async.SelectorWrapper.selectNow(SelectorWrapper.java:26)
11-02 15:47:28.123: E/NIO(8828):    at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:730)
11-02 15:47:28.123: E/NIO(8828):    ... 3 more
```

**Comment by AllenCoder** [comment]
Selector exception, shutting down
                                                           com.koushikdutta.async.AsyncServer$AsyncSelectorException: java.nio.channels.ClosedSelectorException
                                                               at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:757)
                                                               at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:627)
                                                               at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
                                                               at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:569)
                                                            Caused by: java.nio.channels.ClosedSelectorException
                                                               at java.nio.SelectorImpl.checkClosed(SelectorImpl.java:147)
                                                               at java.nio.SelectorImpl.selectInternal(SelectorImpl.java:169)
                                                               at java.nio.SelectorImpl.selectNow(SelectorImpl.java:165)
                                                               at com.koushikdutta.async.SelectorWrapper.selectNow(SelectorWrapper.java:26)
                                                               at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:731)
                                                               at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:627) 
                                                               at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41) 
                                                               at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:569)

**Comment by AllenCoder** [comment]
what' wrong ? how to stop it?

**Comment by CrandellWS** [comment]
related to https://github.com/koush/AndroidAsync/issues/455

**Comment by AnshulMalik** [comment]
I am having the same issue
