### ISSUE TITLE
Selector Exception on Socket Close

### ISSUE THREAD

**Issue by eygraber** [koush/AndroidAsync#280]
I'm seeing this stacktrace in my logs when I close a socket (no crash) using AndroidAsync 2.0.0:

```
E/NIO﹕ Selector exception
com.koushikdutta.async.AsyncServer$AsyncSelectorException: java.nio.channels.ClosedSelectorException
        at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:756)
        at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
        at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
        at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
 Caused by: java.nio.channels.ClosedSelectorException
        at java.nio.SelectorImpl.checkClosed(SelectorImpl.java:142)
        at java.nio.SelectorImpl.selectInternal(SelectorImpl.java:164)
        at java.nio.SelectorImpl.selectNow(SelectorImpl.java:160)
        at com.koushikdutta.async.SelectorWrapper.selectNow(SelectorWrapper.java:26)
        at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:730)
        at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
        at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
        at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
```

**Comment by eygraber** [comment]
Still getting the same StackTrace on 2.1.6; I'm trying to find the source.

**Comment by eygraber** [comment]
Right before this occurs I call:

```
AsyncSSLSocket.close()
AsyncDatagramSocket.close()
// 2 different servers created with new AsyncServer(String)
AsyncServer.stop()
AsyncServer.stop()
```
