### ISSUE TITLE
HybiParser$ProtocolError: RSV not zero

### ISSUE THREAD

**Issue by Keussx** [koush/AndroidAsync#292]
exception introduced when using websockets. The code implementation is similar to https://github.com/koush/AndroidAsync/blob/609d581f793d530191a7950c495c48272c1887ef/AndroidAsync/test/src/com/koushikdutta/async/test/WebSocketTests.java

W/System.err﹕ com.koushikdutta.async.http.HybiParser$ProtocolError: RSV not zero
W/System.err﹕ at com.koushikdutta.async.http.HybiParser.parseOpcode(HybiParser.java:256)
W/System.err﹕ at com.koushikdutta.async.http.HybiParser.access$000(HybiParser.java:46)
W/System.err﹕ at com.koushikdutta.async.http.HybiParser$1.onDataAvailable(HybiParser.java:146)
W/System.err﹕ at com.koushikdutta.async.DataEmitterReader.handlePendingData(DataEmitterReader.java:24)
W/System.err﹕ at com.koushikdutta.async.DataEmitterReader.onDataAvailable(DataEmitterReader.java:41)
W/System.err﹕ at com.koushikdutta.async.Util.emitAllData(Util.java:22)
W/System.err﹕ at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146)
com.kelvin.developer.uniseyshare W/System.err﹕ at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
W/System.err﹕ at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
W/System.err﹕ at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
W/System.err﹕ at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)

**Comment by zouyongdang** [comment]
Did you solve that problem? I  ran into this error too.
