### ISSUE TITLE
Attempt to invoke interface method 'com.koushikdutta.async.AsyncServer com.koushikdutta.async.http.socketio.transport.SocketIOTransport.getServer()' on a null object reference

### ISSUE THREAD

**Issue by jsdevjournal** [koush/AndroidAsync#295]
Hi, I used your library for quite sometimes and it works great.

I have trouble with this error few time (not happen rarely) but I couldn't figure out how to stop this from happenning

java.lang.NullPointerException: Attempt to invoke interface method 'com.koushikdutta.async.AsyncServer com.koushikdutta.async.http.socketio.transport.SocketIOTransport.getServer()' on a null object reference
       at com.koushikdutta.async.http.socketio.SocketIOConnection$3.run(SocketIOConnection.java:180)
       at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:708)
       at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:725)
       at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
       at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
       at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)

This is a full error message, what should I do.

**Comment by qbig** [comment]
Error Message

java.lang.NullPointerException


Where

SocketIOConnection.java:180


Short Stacktrace

0	java.lang.NullPointerException
1	at com.koushikdutta.async.http.socketio.SocketIOConnection$3.run(SocketIOConnection.java:180)
2	at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:708)
3	at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:725)
4	at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
5	at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)

**Comment by jznadams** [comment]
+1 I see this show up on my crash reports pretty regularly

**Comment by behelit** [comment]
This also occurs with regular sockets (non websocket/socketIO tcp)
