### ISSUE TITLE
cannot load get request

### ISSUE THREAD

**Issue by nodegin** [koush/AndroidAsync#299]
I'm using Android 5.0

```
13461-13549/com.testapp.nwt E/art﹕ dlopen("/data/app/com.testapp.nwt-2/lib/arm/libgmscore.so", RTLD_LAZY) failed: dlopen failed: library "/data/app/com.testapp.nwt-2/lib/arm/libgmscore.so" not found
12-16 13:05:10.364  13461-13549/com.testapp.nwt E/ProviderInstaller﹕ Unable to load native code from /data/app/com.testapp.nwt-2/lib/arm/libgmscore.so
12-16 13:05:10.375  13461-13549/com.testapp.nwt E/ProviderInstaller﹕ libgmscore version mismatch (0 vs. 6599)
12-16 13:05:11.077  13461-13461/com.testapp.nwt W/System.err﹕ java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
12-16 13:05:11.078  13461-13461/com.testapp.nwt W/System.err﹕ at com.koushikdutta.async.http.spdy.SpdyMiddleware$4.transform(SpdyMiddleware.java:309)
12-16 13:05:11.078  13461-13461/com.testapp.nwt W/System.err﹕ at com.koushikdutta.async.http.spdy.SpdyMiddleware$4.transform(SpdyMiddleware.java:297)
12-16 13:05:11.078  13461-13461/com.testapp.nwt W/System.err﹕ at com.koushikdutta.async.future.TransformFuture.onCompleted(TransformFuture.java:14)
12-16 13:05:11.078  13461-13461/com.testapp.nwt W/System.err﹕ at com.koushikdutta.async.future.SimpleFuture.handleCallbackUnlocked(SimpleFuture.java:107)
12-16 13:05:11.078  13461-13461/com.testapp.nwt W/System.err﹕ at com.koushikdutta.async.future.SimpleFuture.setComplete(SimpleFuture.java:141)
12-16 13:05:11.078  13461-13461/com.testapp.nwt W/System.err﹕ at com.koushikdutta.async.future.SimpleFuture.setComplete(SimpleFuture.java:128)
12-16 13:05:11.078  13461-13461/com.testapp.nwt W/System.err﹕ at com.koushikdutta.async.http.spdy.AsyncSpdyConnection$SpdySocket.receiveHeaders(AsyncSpdyConnection.java:262)
12-16 13:05:11.078  13461-13461/com.testapp.nwt W/System.err﹕ at com.koushikdutta.async.http.spdy.AsyncSpdyConnection.headers(AsyncSpdyConnection.java:402)
12-16 13:05:11.078  13461-13461/com.testapp.nwt W/System.err﹕ at com.koushikdutta.async.http.spdy.Spdy3$Reader.readSynReply(Spdy3.java:272)
12-16 13:05:11.078  13461-13461/com.testapp.nwt W/System.err﹕ at com.koushikdutta.async.http.spdy.Spdy3$Reader.access$600(Spdy3.java:121)
12-16 13:05:11.078  13461-13461/com.testapp.nwt W/System.err﹕ at com.koushikdutta.async.http.spdy.Spdy3$Reader$3.onDataAvailable(Spdy3.java:208)
12-16 13:05:11.078  13461-13461/com.testapp.nwt W/System.err﹕ at com.koushikdutta.async.DataEmitterReader.handlePendingData(DataEmitterReader.java:24)
12-16 13:05:11.078  13461-13461/com.testapp.nwt W/System.err﹕ at com.koushikdutta.async.DataEmitterReader.onDataAvailable(DataEmitterReader.java:41)
12-16 13:05:11.078  13461-13461/com.testapp.nwt W/System.err﹕ at com.koushikdutta.async.Util.emitAllData(Util.java:22)
12-16 13:05:11.078  13461-13461/com.testapp.nwt W/System.err﹕ at com.koushikdutta.async.AsyncSSLSocketWrapper.onDataAvailable(AsyncSSLSocketWrapper.java:230)
12-16 13:05:11.078  13461-13461/com.testapp.nwt W/System.err﹕ at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:217)
12-16 13:05:11.078  13461-13461/com.testapp.nwt W/System.err﹕ at com.koushikdutta.async.Util.emitAllData(Util.java:22)
12-16 13:05:11.078  13461-13461/com.testapp.nwt W/System.err﹕ at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146)
12-16 13:05:11.078  13461-13461/com.testapp.nwt W/System.err﹕ at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
12-16 13:05:11.078  13461-13461/com.testapp.nwt W/System.err﹕ at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
12-16 13:05:11.078  13461-13461/com.testapp.nwt W/System.err﹕ at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
12-16 13:05:11.079  13461-13461/com.testapp.nwt W/System.err﹕ at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
12-16 13:05:11.738 
```

**Comment by nodegin** [comment]
After 3 months still can see this error..wow

**Comment by koush** [comment]
It is not an error. It is benign. Its just a byproduct of using GMS conscrypt in the log. Your app didn't crash.

**Comment by nodegin** [comment]
I think you should update the readme.md **Download** paragraph, and add GMS dependency

**Comment by koush** [comment]
It's an optional dependency.

**Comment by Abhi0725** [comment]
@koush I am also facing this issue. Can you please suggest what is the reason?
