### ISSUE TITLE
TLS Connection Failed (with generic SSLException)

### ISSUE THREAD

**Issue by vladislavdonchev** [koush/AndroidAsync#314]
Hello,

I am writing a WebSocket client application, but I am facing an issue with the implementation of TLS. My server is Grizzly 2.3.18 based and I am using a self-signed key store. The original key-store file is in JKS format, so I've converted it in BKS for the Android side (with Portecle).

There are no errors when the key stores are loaded and initialized on both the server and client sides and everything seems to be in working order when I attempt to initialize the WebSocket connection.
Here's my client code:

        SSLContext sslContext = null;
        TrustManagerFactory tmf = null;

        try {
            KeyManagerFactory kmf = KeyManagerFactory.getInstance("X509");
            KeyStore ks = KeyStore.getInstance(KeyStore.getDefaultType());

            ks.load(getResources().openRawResource(R.raw.keystore), "pass".toCharArray());
            kmf.init(ks, "pass".toCharArray());

            tmf = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
            KeyStore ts = KeyStore.getInstance(KeyStore.getDefaultType());
            ts.load(getResources().openRawResource(R.raw.keystore), "pass".toCharArray());
            tmf.init(ts);

            sslContext = SSLContext.getInstance("TLSv1.2");
            sslContext.init(kmf.getKeyManagers(), tmf.getTrustManagers(), null);
        } catch (Exception e){
            Log.d("SSLCONFIG", e.toString(), e);
        }

        String address = preferences.getString("server", "192.168.0.104:8021/tp");

        AsyncHttpClient.getDefaultInstance().getSSLSocketMiddleware().setSSLContext(sslContext);
        AsyncHttpClient.getDefaultInstance().getSSLSocketMiddleware().setTrustManagers(tmf.getTrustManagers());
        AsyncHttpClient.getDefaultInstance().getSSLSocketMiddleware().setConnectAllAddresses(true);
        AsyncHttpClient.getDefaultInstance().websocket("wss://" + address, null, webSocketCallback);

Almost immediately the WebSocketConnectCallback is called with a null WebSocket object and shortly after an SSLException follows:

    javax.net.ssl.SSLException
            at com.koushikdutta.async.AsyncSSLSocketWrapper$2.onCompleted(AsyncSSLSocketWrapper.java:106)
            at com.koushikdutta.async.AsyncNetworkSocket.reportClose(AsyncNetworkSocket.java:172)
            at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:154)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)

Could you please let me know if there is any way to further debug this? Unfortunately this exception has no cause and a very limited stack trace, so it is quite hard to guess what may be causing it...

In the meanwhile I will try to investigate the issue a bit more on the server side, where there are no errors and exceptions at all. :( I did a tcpdump trace and I can see that there are about a dozen packets bounced between the two endpoints before I finally see the SSLException on the client, so there is definitely something more going on.

Finally, without the TLS configuration the WebSocket connection is working flawlessly...

Regards,
Vlad

**Comment by vladislavdonchev** [comment]
OK, so this turned out to be a 2-part problem:

1. On my server, I was setting the keyStore password with sslContextConfigurator.setKeyStorePass(...) instead of just .setKeyPass(...), which wasn't producing an exception, but resulted in a bad TLS configuration.

2. After fixing the above issue, I had to change my TrustManager config on the client side to accept self-signed keys:

        AsyncHttpClient.getDefaultInstance().getSSLSocketMiddleware().setTrustManagers(new TrustManager[] {
                new X509TrustManager() {
                    public void checkClientTrusted(X509Certificate[] chain, String authType) {}
                    public void checkServerTrusted(X509Certificate[] chain, String authType) {}
                    public X509Certificate[] getAcceptedIssuers() { return new X509Certificate[]{}; }
                }
        });

After doing this everything started working as expected.
Closing issue... :)
