### ISSUE TITLE
Not all data was consumed by Util.emitAllData

### ISSUE THREAD

**Issue by JoshElias** [koush/AndroidAsync#330]
I'm not sure why I'm getting this error when trying to handle POST request. Please help!

03-10 20:56:49.920: W/System.err(17882): java.lang.RuntimeException: Not all data was consumed by Util.emitAllData
03-10 20:56:49.920: W/System.err(17882): 	at com.koushikdutta.async.Util.emitAllData(Util.java:47)
03-10 20:56:49.920: W/System.err(17882): 	at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
03-10 20:56:49.920: W/System.err(17882): 	at com.koushikdutta.async.http.server.BoundaryEmitter.onDataAvailable(BoundaryEmitter.java:163)
03-10 20:56:49.920: W/System.err(17882): 	at com.koushikdutta.async.Util.emitAllData(Util.java:22)
03-10 20:56:49.920: W/System.err(17882): 	at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
03-10 20:56:49.920: W/System.err(17882): 	at com.koushikdutta.async.http.filter.ContentLengthFilter.onDataAvailable(ContentLengthFilter.java:33)
03-10 20:56:49.920: W/System.err(17882): 	at com.koushikdutta.async.Util.emitAllData(Util.java:22)
03-10 20:56:49.920: W/System.err(17882): 	at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146)
03-10 20:56:49.930: W/System.err(17882): 	at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
03-10 20:56:49.930: W/System.err(17882): 	at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
03-10 20:56:49.930: W/System.err(17882): 	at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
03-10 20:56:49.930: W/System.err(17882): 	at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)

**Comment by JoshElias** [comment]
Is this library being supported any more?

**Comment by koush** [comment]
Yes.

What are you posting?

**Comment by JoshElias** [comment]
It should be JSON. It's odd that sometimes it comes through as a UrlEncodedFormBody and other times it comes through as a MultipartFormDataBody. It's when a multipart is passed that it errors.

**Comment by emacstheviking** [comment]
I am having a similar problem with POST but no error, just no data. I have spent five days trying to figure it out. I thought it was me using CURL command line with wrong optins so I wrote a short Python program to do the upload same problem.

I thought it was to do with the 100-continue operation but it isn't. However the end result is the same; I get the message content up tot the 100-continue but no more.

There is no sample documentation or examples that I can find that shows how to correctly receive a POST multipart/form-data from the client. I want to be able to send data to my app. to update things and being able to use POST is vital.

I am currently looking at NanoHTTPD but I liked your solution better until this POST thing!

I am still investigating the issue but it's taking time because the code is still foreign to me.

Any help, advice, samples etc, that anybody has on how to send POST multipart/form-data into the server would be most gratefully received.

Thank you.
Sean Charles.
