### ISSUE TITLE
CacheMiddleware crashing the process

### ISSUE THREAD

**Issue by schwiz** [koush/AndroidAsync#358]
Using the version of AndroidAsync that is included with ion 2.1.4 I'm getting frequent uncatchable exceptions from AndroidAsync.  Any advice on what I can do to prevent this would be great it sadly may force me to switch to a different networking stack :/

```
java.lang.RuntimeException: Not all data was consumed by Util.emitAllData
       at com.koushikdutta.async.Util.emitAllData(Util.java:47)
       at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
       at com.koushikdutta.async.http.cache.ResponseCacheMiddleware$CachedBodyEmitter.spewInternal(ResponseCacheMiddleware.java:428)
       at com.koushikdutta.async.http.cache.ResponseCacheMiddleware$1.run(ResponseCacheMiddleware.java:172)
       at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:708)
       at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:725)
       at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
       at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
       at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
```

**Comment by schwiz** [comment]
@koush any update or thoughts? This is the number one reported crash after our first week of launch.

**Comment by koush** [comment]
Gonna be tackling the backlog of ion and andoridasync issues soon. I thought I had fixed this, but I guess not.

**Comment by koush** [comment]
Incidentally, this exception is meant to catch bad/misbehaving network behavior. If you have a forked version, you could just clear the bytebufferlist and comment out hte exception.

**Comment by koush** [comment]
I actually have a few of these types of exceptions sprinkled through the code. Honestly, these should be assertions. I think what I'll do is leave the exception in, but only conditionally throw it. The condition will be enabled by default. But you can disable it via some config option. Like Ion.getDefault(context).configure().debugExceptions(false).

Lemme know if that would work for you.

**Comment by schwiz** [comment]
Thanks for the reply @koush I'm really open to suggestions, currently I'm just pulling in from maven and haven't forked. I don't really grok what spewInternal is supposed to be doing, what are the repercussions of not throwing the error? I'm not sure that allowing the client to continue but with the network stack in a bad state would be preferable.

**Comment by koush** [comment]
Nah, basically what is happening, is that a request is getting cancelled, and that should cancel any data from being sent from that socket. It's sending it anyways though. This data goes unhandled, and the exception is thrown.

As I said, it's more just an exception that helps me catch potential protocol errors. In this case, the error is that when a request fulfilled from the cache is cancelled, the cache should stop the response, but it doesn't.

No repercussions from removing that error.

**Comment by schwiz** [comment]
Okay so is this a threading issue then, because I see the emitAllData method that is throwing the exception checked to see if the emitter has been canceled before throwing the exception.  

Your suggestion about turning these exceptions off with the configure method in ion works for me knowing it won't cause funny behavior.

**Comment by koush** [comment]
Yeah likely a threading issue of some sort

**Comment by schwiz** [comment]
Okay, do you have a timeline rough for your proposed change to suppress
these exceptions in ion?

On Tue, Jun 9, 2015 at 3:50 PM, Koushik Dutta <notifications@github.com>
wrote:

> Yeah likely a threading issue of some sort
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/koush/AndroidAsync/issues/358#issuecomment-110500249>.
>



-- 
*Nathan Schwermann*
*785-312-0080*
*http://schwiz.net <http://schwiz.net>*

**Comment by koush** [comment]
Lemme knock it out right now

**Comment by schwiz** [comment]
Sweet thanks!

On Tue, Jun 9, 2015 at 4:02 PM, Koushik Dutta <notifications@github.com>
wrote:

> Lemme knock it out right now
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/koush/AndroidAsync/issues/358#issuecomment-110503113>.
>



-- 
*Nathan Schwermann*
*785-312-0080*
*http://schwiz.net <http://schwiz.net>*

**Comment by koush** [comment]
https://github.com/koush/AndroidAsync/commit/e49bd233c187e3e754e96dc6481b6047bf98f112

**Comment by koush** [comment]
So just set Util.SUPRESS_DEBUG_EXCEPTIONS to true and it should mask the error until i can figure out the race condition around cache cancelling

**Comment by koush** [comment]
ok released in 215. leaving this bug open.

**Comment by schwiz** [comment]
Thanks for the quick turn around on this. So its in maven now?

On Tue, Jun 9, 2015 at 4:08 PM, Koushik Dutta <notifications@github.com>
wrote:

> ok released in 215. leaving this bug open.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/koush/AndroidAsync/issues/358#issuecomment-110504795>.
>



-- 
*Nathan Schwermann*
*785-312-0080*
*http://schwiz.net <http://schwiz.net>*

**Comment by koush** [comment]
yeah may take a few hours to roll out

**Comment by schwiz** [comment]
@koush you didn't make it a public value so I can't set it to true

**Comment by koush** [comment]
Damnit, I swear I had a second commit that did that. I guess I didn't save and commit.

**Comment by schwiz** [comment]
Whoops, do you plan to just re-submit 2.1.5 to maven or will you bump it up to 6?

**Comment by koush** [comment]
Just built and published 216

**Comment by koush** [comment]
This might be the actual fix:

6c36806

**Comment by koush** [comment]
derp tagging @schwiz

**Comment by schwiz** [comment]
Awesome thanks for the heads up! Is the potential fix in 216 or coming
later?

**Comment by koush** [comment]
Later, need to charge my phone(s) to run the tests

**Comment by chrsvl** [comment]
Hi Koush,

Any news on the issue? I am still getting it :(
