### ISSUE TITLE
SSL handshake fails with self signed certificate on Android 4.3 (and 4.2.2)

### ISSUE THREAD

**Issue by nbrocard** [koush/AndroidAsync#393]
When trying to connect to a HTTPS url with AndroidAsync, I get the following stacktrace :
```java
 javax.net.ssl.SSLException: Fatal alert received handshake_failure
 at org.apache.harmony.xnet.provider.jsse.SSLEngineImpl.unwrap(SSLEngineImpl.java:485)
 at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:383)
 at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:191)
 at com.koushikdutta.async.Util.emitAllData(Util.java:23)
 at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146)
 at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
 at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
 at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
 at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
```

Here is the code I use :
```java
        SSLContext sslcontext = null;
        TrustManager[] trustManagers = null;
        try {
            trustManagers = CertUtils.getTrustManagers(mContext);
            sslcontext = SSLContext.getInstance("TLS");
            sslcontext.init(null, trustManagers, null);
        } catch (NoSuchAlgorithmException | KeyManagementException | CertificateException | IOException | KeyStoreException e) {
            e.printStackTrace();
        }

        AsyncHttpClient asyncHttpClient = AsyncHttpClient.getDefaultInstance();
        asyncHttpClient.insertMiddleware(new ConscryptMiddleware(mContext, asyncHttpClient.getSSLSocketMiddleware()));
        asyncHttpClient.getSSLSocketMiddleware().setSSLContext(sslcontext);
        asyncHttpClient.getSSLSocketMiddleware().setTrustManagers(trustManagers);

        asyncHttpClient.execute("https://url:443", new HttpConnectCallback() {
            @Override
            public void onConnectCompleted(Exception ex, AsyncHttpResponse response) {
                if (ex != null) {
                    Log.e("AsyncTest", "exception ? " + ex);
                }
                if (response != null) {
                    Log.d("AsyncTest", "result : " + response.code());
                }

            }
        });
```
I load custom CA from assets. The SSL context I use here works when I try to connect using HttpsUrlConnection :

```java
        try {
            URL url = new URL("https://url:443");
            final HttpsURLConnection urlConnection = (HttpsURLConnection) url.openConnection();
            urlConnection.setSSLSocketFactory(sslcontext.getSocketFactory());
            new Thread() {
                @Override
                public void run() {
                    try {
                        urlConnection.connect();
                        InputStream inputStream = urlConnection.getInputStream();

                        //read stream

                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
            }.start();
        } catch (MalformedURLException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
```

It works on Android M preview 3, maybe because of conscrypt used by default ?

**Comment by nbrocard** [comment]
Hum after looking at Ion, it seems that conscrypt fixes this issue, so I tried to initialize conscrypt the same way ConscryptMiddleware does. I enventually made it working after removing this part :
```java
                Provider[] providers = Security.getProviders();
                Provider provider = Security.getProvider(GMS_PROVIDER);
                Security.removeProvider(GMS_PROVIDER);
                Security.insertProviderAt(provider, providers.length);
```
On Android 4.3 and latest GMS if other security provider than GMS one is used, TrustManager fails with a java.security.cert.CertPathValidatorException : 
```java
javax.net.ssl.SSLHandshakeException: Handshake failed
     at com.google.android.gms.org.conscrypt.OpenSSLEngineImpl.unwrap(SourceFile:441)
     at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:383)
     at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:194)
     at com.koushikdutta.async.Util.emitAllData(Util.java:23)
     at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146)
     at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:789)
     at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:627)
     at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
     at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:569)
  Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
     at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:282)
     at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:192)
     at com.google.android.gms.org.conscrypt.Platform.checkServerTrusted(SourceFile:164)
     at com.google.android.gms.org.conscrypt.OpenSSLEngineImpl.verifyCertificateChain(SourceFile:666)
     at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake_bio(Native Method)
     at com.google.android.gms.org.conscrypt.OpenSSLEngineImpl.unwrap(SourceFile:426)
     at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:383) 
     at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:194) 
     at com.koushikdutta.async.Util.emitAllData(Util.java:23) 
     at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146) 
     at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:789) 
     at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:627) 
     at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41) 
     at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:569) 
  Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
     at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:282) 
     at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:192) 
     at com.google.android.gms.org.conscrypt.Platform.checkServerTrusted(SourceFile:164) 
     at com.google.android.gms.org.conscrypt.OpenSSLEngineImpl.verifyCertificateChain(SourceFile:666) 
     at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake_bio(Native Method) 
     at com.google.android.gms.org.conscrypt.OpenSSLEngineImpl.unwrap(SourceFile:426) 
     at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:383) 
     at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:194) 
     at com.koushikdutta.async.Util.emitAllData(Util.java:23) 
     at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146) 
     at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:789) 
     at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:627) 
     at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41) 
     at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:569) 
```

I tested with Ion and I ended with the same error.

**Comment by bleuf1sh** [comment]
I'm having the same issue on a Samsung Mega running 4.2.2
```
10-20 11:05:02.131: D/ExampleLogoutUtilsREQ(9413): (0 ms) https://stagingcdn.example.com/logout?l=en&cv=9999999&dl=en&os=a&sv=5&sid=MTsxOzUzZjllZWMyZGIxYTdkMWMwOGMyNGNlODs1OzJmYTdhYTZhOWM4NzZmMmRjOWM1OGNiMGEwODkyZjIxO2E0MzU1NjFkZTdiM2U3OWQ0NjZjZDNkNGZmNzEzZWQ0QQ%3D%3D: Executing request.
10-20 11:05:02.141: D/ExampleLogoutUtilsREQ(9413): (6 ms) https://stagingcdn.example.com/logout?l=en&cv=9999999&dl=en&os=a&sv=5&sid=MTsxOzUzZjllZWMyZGIxYTdkMWMwOGMyNGNlODs1OzJmYTdhYTZhOWM4NzZmMmRjOWM1OGNiMGEwODkyZjIxO2E0MzU1NjFkZTdiM2U3OWQ0NjZjZDNkNGZmNzEzZWQ0QQ%3D%3D: Connecting socket
10-20 11:05:02.451: V/ExampleLogoutUtilsREQ(9413): (314 ms) https://stagingcdn.example.com/logout?l=en&cv=9999999&dl=en&os=a&sv=5&sid=MTsxOzUzZjllZWMyZGIxYTdkMWMwOGMyNGNlODs1OzJmYTdhYTZhOWM4NzZmMmRjOWM1OGNiMGEwODkyZjIxO2E0MzU1NjFkZTdiM2U3OWQ0NjZjZDNkNGZmNzEzZWQ0QQ%3D%3D: socket connected
10-20 11:05:02.451: E/ExampleLogoutUtilsREQ(9413): (314 ms) https://stagingcdn.example.com/logout?l=en&cv=9999999&dl=en&os=a&sv=5&sid=MTsxOzUzZjllZWMyZGIxYTdkMWMwOGMyNGNlODs1OzJmYTdhYTZhOWM4NzZmMmRjOWM1OGNiMGEwODkyZjIxO2E0MzU1NjFkZTdiM2U3OWQ0NjZjZDNkNGZmNzEzZWQ0QQ%3D%3D: Connection error
10-20 11:05:02.451: E/ExampleLogoutUtilsREQ(9413): null
10-20 11:05:02.451: E/ExampleLogoutUtilsREQ(9413): javax.net.ssl.SSLException
10-20 11:05:02.451: E/ExampleLogoutUtilsREQ(9413):    at com.koushikdutta.async.AsyncSSLSocketWrapper$2.onCompleted(AsyncSSLSocketWrapper.java:106)
10-20 11:05:02.451: E/ExampleLogoutUtilsREQ(9413):    at com.koushikdutta.async.AsyncNetworkSocket.reportClose(AsyncNetworkSocket.java:172)
10-20 11:05:02.451: E/ExampleLogoutUtilsREQ(9413):    at com.koushikdutta.async.AsyncNetworkSocket.close(AsyncNetworkSocket.java:180)
10-20 11:05:02.451: E/ExampleLogoutUtilsREQ(9413):    at com.koushikdutta.async.AsyncSSLSocketWrapper.report(AsyncSSLSocketWrapper.java:424)
10-20 11:05:02.451: E/ExampleLogoutUtilsREQ(9413):    at com.koushikdutta.async.AsyncSSLSocketWrapper.access$100(AsyncSSLSocketWrapper.java:30)
10-20 11:05:02.451: E/ExampleLogoutUtilsREQ(9413):    at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:221)
10-20 11:05:02.451: E/ExampleLogoutUtilsREQ(9413):    at com.koushikdutta.async.Util.emitAllData(Util.java:22)
10-20 11:05:02.451: E/ExampleLogoutUtilsREQ(9413):    at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146)
10-20 11:05:02.451: E/ExampleLogoutUtilsREQ(9413):    at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
10-20 11:05:02.451: E/ExampleLogoutUtilsREQ(9413):    at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
10-20 11:05:02.451: E/ExampleLogoutUtilsREQ(9413):    at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
10-20 11:05:02.451: E/ExampleLogoutUtilsREQ(9413):    at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
10-20 11:05:02.451: V/ExampleLogoutUtilsREQ(9413): (316 ms) https://stagingcdn.example.com/logout?l=en&cv=9999999&dl=en&os=a&sv=5&sid=MTsxOzUzZjllZWMyZGIxYTdkMWMwOGMyNGNlODs1OzJmYTdhYTZhOWM4NzZmMmRjOWM1OGNiMGEwODkyZjIxO2E0MzU1NjFkZTdiM2U3OWQ0NjZjZDNkNGZmNzEzZWQ0QQ%3D%3D: socket connected
10-20 11:05:02.451: E/ExampleLogoutUtilsREQ(9413): (316 ms) https://stagingcdn.example.com/logout?l=en&cv=9999999&dl=en&os=a&sv=5&sid=MTsxOzUzZjllZWMyZGIxYTdkMWMwOGMyNGNlODs1OzJmYTdhYTZhOWM4NzZmMmRjOWM1OGNiMGEwODkyZjIxO2E0MzU1NjFkZTdiM2U3OWQ0NjZjZDNkNGZmNzEzZWQ0QQ%3D%3D: Connection error
10-20 11:05:02.451: E/ExampleLogoutUtilsREQ(9413): Fatal alert received handshake_failure
10-20 11:05:02.451: E/ExampleLogoutUtilsREQ(9413): javax.net.ssl.SSLException: Fatal alert received handshake_failure
10-20 11:05:02.451: E/ExampleLogoutUtilsREQ(9413):    at org.apache.harmony.xnet.provider.jsse.SSLEngineImpl.unwrap(SSLEngineImpl.java:485)
10-20 11:05:02.451: E/ExampleLogoutUtilsREQ(9413):    at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:383)
10-20 11:05:02.451: E/ExampleLogoutUtilsREQ(9413):    at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:191)
10-20 11:05:02.451: E/ExampleLogoutUtilsREQ(9413):    at com.koushikdutta.async.Util.emitAllData(Util.java:22)
10-20 11:05:02.451: E/ExampleLogoutUtilsREQ(9413):    at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146)
10-20 11:05:02.451: E/ExampleLogoutUtilsREQ(9413):    at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
10-20 11:05:02.451: E/ExampleLogoutUtilsREQ(9413):    at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
10-20 11:05:02.451: E/ExampleLogoutUtilsREQ(9413):    at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
10-20 11:05:02.451: E/ExampleLogoutUtilsREQ(9413):    at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
```

**Comment by bleuf1sh** [comment]
we're experiencing the same issue. 

@koush is there a way to fix this? or is the "fix" to simply use ion instead of AndroidAsync?

**Comment by NVentimiglia** [comment]
Getting this on Android 4.4.4

**Comment by sveilleux1** [comment]
I confirm I also get this on Android 4.4.4

**Comment by blazmag** [comment]
+1

**Comment by rajohns08** [comment]
If you simply want to trust all certificates (which is very insecure), you could do the following which worked for me:

```java
Uri uri = Uri.parse("https://myurl.com");
AsyncHttpRequest request = new AsyncHttpRequest(uri, "GET");
AsyncHttpClient asyncHttpClient = AsyncHttpClient.getDefaultInstance();
SSLContext sslContext = null;
TrustManager[] trustManagers = null;
try {
    sslContext = SSLContext.getInstance("TLS");
    trustManagers = new TrustManager[] {
        new X509TrustManager() {
            public void checkClientTrusted(X509Certificate[] chain, String authType) {}
            public void checkServerTrusted(X509Certificate[] chain, String authType) {}
            public X509Certificate[] getAcceptedIssuers() { return new X509Certificate[]{}; }
        }
    };
    try {
        sslContext.init(null, trustManagers, null);
    } catch (KeyManagementException e) {
        e.printStackTrace();
    }
} catch (NoSuchAlgorithmException e) {
    e.printStackTrace();
}
asyncHttpClient.getSSLSocketMiddleware().setSSLContext(sslContext);
asyncHttpClient.getSSLSocketMiddleware().setTrustManagers(trustManagers);
asyncHttpClient.getSSLSocketMiddleware().setHostnameVerifier(new HostnameVerifier() {
    @Override
    public boolean verify(String s, SSLSession sslSession) {
        return true;
    }
});
asyncHttpClient.websocket(request, null, new AsyncHttpClient.WebSocketConnectCallback() {
    @Override
    public void onCompleted(Exception ex, WebSocket webSocket) {
        if (ex != null) {
            ex.printStackTrace();
        } else {
            webSocket.setStringCallback(new WebSocket.StringCallback() {
                @Override
                public void onStringAvailable(String s) {
                    Log.d("mytag", s);
                }
            });
            webSocket.send("hola");
        }
    }
});
```
