### ISSUE TITLE
java.nio.channels.CancelledKeyException

### ISSUE THREAD

**Issue by RubenKid** [koush/AndroidAsync#407]
Issue https://github.com/koush/AndroidAsync/issues/236 still happening in 2.1.6 Version:

```
java.nio.channels.CancelledKeyException
	at java.nio.SelectionKeyImpl.checkValid(SelectionKeyImpl.java:101)
	at java.nio.SelectionKeyImpl.interestOps(SelectionKeyImpl.java:69)
	at com.koushikdutta.async.AsyncNetworkSocket.handleRemaining(AsyncNetworkSocket.java:105)
	at com.koushikdutta.async.AsyncNetworkSocket.write(AsyncNetworkSocket.java:85)
	at com.koushikdutta.async.Util$8.onWriteable(Util.java:201)
	at com.koushikdutta.async.Util.writeAll(Util.java:208)
	at com.koushikdutta.async.Util.writeAll(Util.java:216)
	at com.koushikdutta.async.http.HttpTransportMiddleware.exchangeHeaders(HttpTransportMiddleware.java:45)
	at com.koushikdutta.async.http.AsyncHttpClient.executeSocket(AsyncHttpClient.java:485)
	at com.koushikdutta.async.http.AsyncHttpClient.access$300(AsyncHttpClient.java:50)
	at com.koushikdutta.async.http.AsyncHttpClient$3.onConnectCompleted(AsyncHttpClient.java:287)
	at com.koushikdutta.async.http.AsyncSocketMiddleware.getSocket(AsyncSocketMiddleware.java:156)
	at com.koushikdutta.async.http.AsyncHttpClient.executeAffinity(AsyncHttpClient.java:303)
	at com.koushikdutta.async.http.AsyncHttpClient.access$100(AsyncHttpClient.java:50)
	at com.koushikdutta.async.http.AsyncHttpClient$1.run(AsyncHttpClient.java:189)
	at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:708)
	at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:725)
	at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
	at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
	at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
```

Thanks!

**Comment by 3c133ps3d** [comment]
I met same problem at 3.0.8:

```
Fatal Exception: java.nio.channels.CancelledKeyException
       at sun.nio.ch.SelectionKeyImpl.ensureValid + 73(SelectionKeyImpl.java:73)
       at sun.nio.ch.SelectionKeyImpl.interestOps + 82(SelectionKeyImpl.java:82)
       at com.koushikdutta.async.AsyncNetworkSocket.handleRemaining + 113(AsyncNetworkSocket.java:113)
       at com.koushikdutta.async.AsyncNetworkSocket.write + 91(AsyncNetworkSocket.java:91)
       at com.koushikdutta.async.BufferedDataSink.write + 79(BufferedDataSink.java:79)
       at com.koushikdutta.async.AsyncSSLSocketWrapper.write + 494(AsyncSSLSocketWrapper.java:494)
       at com.koushikdutta.async.BufferedDataSink.write + 79(BufferedDataSink.java:79)
       at com.koushikdutta.async.http.WebSocketImpl.lambda$send$0 + 239(WebSocketImpl.java:239)
       at com.koushikdutta.async.http.-$$Lambda$WebSocketImpl$5NBIaX1nvYBX3mbDX2Puj7dd1Lg.run(-.java)
       at com.koushikdutta.async.AsyncServer$Scheduled.run + 236(AsyncServer.java:236)
       at com.koushikdutta.async.AsyncServer.lockAndRunQueue + 788(AsyncServer.java:788)
       at com.koushikdutta.async.AsyncServer.runLoop + 806(AsyncServer.java:806)
       at com.koushikdutta.async.AsyncServer.run + 717(AsyncServer.java:717)
       at com.koushikdutta.async.AsyncServer.access$800 + 46(AsyncServer.java:46)
       at com.koushikdutta.async.AsyncServer$11.run + 671(AsyncServer.java:671)
```
