### ISSUE TITLE
send() hangs

### ISSUE THREAD

**Issue by 4ntoine** [koush/AndroidAsync#431]
```
java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Thread.parkFor(Thread.java:1205)
	  at sun.misc.Unsafe.park(Unsafe.java:325)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:813)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:973)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1281)
	  at java.util.concurrent.Semaphore.acquire(Semaphore.java:283)
	  at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:199)
	  at com.koushikdutta.async.AsyncNetworkSocket.write(AsyncNetworkSocket.java:67)
	  at com.koushikdutta.async.BufferedDataSink.write(BufferedDataSink.java:54)
	  at com.koushikdutta.async.BufferedDataSink.write(BufferedDataSink.java:49)
	  at com.koushikdutta.async.AsyncSSLSocketWrapper.write(AsyncSSLSocketWrapper.java:387)
	  at com.koushikdutta.async.BufferedDataSink.write(BufferedDataSink.java:54)
	  at com.koushikdutta.async.BufferedDataSink.write(BufferedDataSink.java:49)
	  at com.koushikdutta.async.http.WebSocketImpl.send(WebSocketImpl.java:233)
	  at com.company.ws.WSClientRPC.sendString(WSClientRPC.java:592)
	  at com.company.ws.WSClientRPC$2.run(WSClientRPC.java:378)
	  at java.lang.Thread.run(Thread.java:841)
```

**Comment by egslava** [comment]
Is it resolved?

**Comment by egslava** [comment]
I bumped into the same error. Is there some workaround?

**Comment by egslava** [comment]
Please, take a look into this thread:
https://github.com/koush/AndroidAsync/issues/310
