### ISSUE TITLE
WSS is not working on Android 4.0.x

### ISSUE THREAD

**Issue by TomWangTW** [koush/AndroidAsync#510]
I use this project to make a websocket security server and it works great, but when i test my project on some devices which android version is 4.0.x then it got fail.
    After i add some log to trace it, i found it always got null on callback of listenSecure method.

============================

@Override
            public void onAccepted(AsyncSocket socket) {
                AsyncSSLSocketWrapper.handshake(socket, null, port, sslContext.createSSLEngine(), null, null, false,
                new AsyncSSLSocketWrapper.HandshakeCallback() {
                    @Override
                    public void onHandshakeCompleted(Exception e, AsyncSSLSocket **socket**) {
                        if (socket != null) {
                            logger.debug("onHandshakeCompleted onAccepted ");
                            mListenCallback.onAccepted(socket);
                        } else {
                            logger.debug("onHandshakeCompleted non onAccepted");
                        }
                    }
                });
            }

**Comment by TomWangTW** [comment]
After print the error message, it looks like TLS version not support.
01-18 09:24:27.710: D/AsyncHttpServer(8907): onHandshakeCompleted Exception Error occured in delegated task:javax.net.ssl.SSLHandshakeException: PROTOCOL VERSION. Unsupported client version 33
01-18 09:24:27.710: W/System.err(8907): javax.net.ssl.SSLException: Error occured in delegated task:javax.net.ssl.SSLHandshakeException: PROTOCOL VERSION. Unsupported client version 33
01-18 09:24:27.710: W/System.err(8907): 	at org.apache.harmony.xnet.provider.jsse.HandshakeProtocol.fatalAlert(HandshakeProtocol.java:319)
01-18 09:24:27.710: W/System.err(8907): 	at org.apache.harmony.xnet.provider.jsse.HandshakeProtocol.wrap(HandshakeProtocol.java:271)
01-18 09:24:27.710: W/System.err(8907): 	at org.apache.harmony.xnet.provider.jsse.SSLEngineImpl.wrap(SSLEngineImpl.java:694)
01-18 09:24:27.710: W/System.err(8907): 	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:438)
01-18 09:24:27.710: W/System.err(8907): 	at com.koushikdutta.async.AsyncSSLSocketWrapper.write(AsyncSSLSocketWrapper.java:386)
01-18 09:24:27.710: W/System.err(8907): 	at com.koushikdutta.async.AsyncSSLSocketWrapper.handleHandshakeStatus(AsyncSSLSocketWrapper.java:276)
01-18 09:24:27.715: W/System.err(8907): 	at com.koushikdutta.async.AsyncSSLSocketWrapper.access$000(AsyncSSLSocketWrapper.java:30)
01-18 09:24:27.715: W/System.err(8907): 	at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:213)
01-18 09:24:27.715: W/System.err(8907): 	at com.koushikdutta.async.Util.emitAllData(Util.java:23)
01-18 09:24:27.715: W/System.err(8907): 	at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
01-18 09:24:27.715: W/System.err(8907): 	at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:821)
01-18 09:24:27.715: W/System.err(8907): 	at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658)
01-18 09:24:27.715: W/System.err(8907): 	at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
01-18 09:24:27.715: W/System.err(8907): 	at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600)

**Comment by pookie13** [comment]
Hey TomWangTW,
 have you found any solution for this because we are also facing the same issue. and can you please let me know how to add our certificates of the server into client side which cause handshaking failure in some devices.

thanks in advance :)

**Comment by TomWangTW** [comment]
Hi @pookie13 

Sorry for late response.
Question 1:
No, i do not have solution yet. I think the older android versions appear to have buggy ssl implementation.
Question 2:
Can you describe more clearly?
