### ISSUE TITLE
Array out of index exception

### ISSUE THREAD

**Issue by AlfredAfutu** [koush/AndroidAsync#517]
I am trying to connect to a device using wifi but i cannot establish connection. I get this stack trace. Please help

02-07 16:37:57.954 9482-11510/com.geoodk.collect.android W/System.err: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
02-07 16:37:57.954 9482-11510/com.geoodk.collect.android W/System.err:     at com.koushikdutta.async.http.socketio.SocketIOConnection$2.transform(SocketIOConnection.java:118)
02-07 16:37:57.954 9482-11510/com.geoodk.collect.android W/System.err:     at com.koushikdutta.async.http.socketio.SocketIOConnection$2.transform(SocketIOConnection.java:113)
02-07 16:37:57.954 9482-11510/com.geoodk.collect.android W/System.err:     at com.koushikdutta.async.future.TransformFuture.onCompleted(TransformFuture.java:14)
02-07 16:37:57.954 9482-11510/com.geoodk.collect.android W/System.err:     at com.koushikdutta.async.future.SimpleFuture.handleCallbackUnlocked(SimpleFuture.java:107)
02-07 16:37:57.954 9482-11510/com.geoodk.collect.android W/System.err:     at com.koushikdutta.async.future.SimpleFuture.setComplete(SimpleFuture.java:141)
02-07 16:37:57.954 9482-11510/com.geoodk.collect.android W/System.err:     at com.koushikdutta.async.future.SimpleFuture.setComplete(SimpleFuture.java:128)
02-07 16:37:57.954 9482-11510/com.geoodk.collect.android W/System.err:     at com.koushikdutta.async.http.AsyncHttpClient.invokeWithAffinity(AsyncHttpClient.java:523)
02-07 16:37:57.954 9482-11510/com.geoodk.collect.android W/System.err:     at com.koushikdutta.async.http.AsyncHttpClient.access$800(AsyncHttpClient.java:51)
02-07 16:37:57.954 9482-11510/com.geoodk.collect.android W/System.err:     at com.koushikdutta.async.http.AsyncHttpClient$7.run(AsyncHttpClient.java:534)
02-07 16:37:57.954 9482-11510/com.geoodk.collect.android W/System.err:     at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:739)
02-07 16:37:57.954 9482-11510/com.geoodk.collect.android W/System.err:     at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:757)
02-07 16:37:57.954 9482-11510/com.geoodk.collect.android W/System.err:     at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:657)
02-07 16:37:57.954 9482-11510/com.geoodk.collect.android W/System.err:     at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
02-07 16:37:57.954 9482-11510/com.geoodk.collect.android W/System.err:     at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:599)

**Comment by meUser07** [comment]
@AlfredAfutu  Have u found any solution for this issue?
