### ISSUE TITLE
Issue #491 is still unresolved : invalid deflated data

### ISSUE THREAD

**Issue by Kartik-RTP** [koush/AndroidAsync#523]
i am getting the same error
java.io.IOException: Invalid deflated data
at com.koushikdutta.async.http.HybiParser.emitFrame(HybiParser.java:407)
at com.koushikdutta.async.http.HybiParser.access$800(HybiParser.java:46)
at com.koushikdutta.async.http.HybiParser$5.onDataAvailable(HybiParser.java:203)
at com.koushikdutta.async.DataEmitterReader.handlePendingData(DataEmitterReader.java:24)
at com.koushikdutta.async.DataEmitterReader.onDataAvailable(DataEmitterReader.java:41)
at com.koushikdutta.async.Util.emitAllData(Util.java:23)
at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:820)
at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:657)
at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:599)

Help me how to resolve it ...................I am sending a basic string only

**Comment by Kartik-RTP** [comment]
got it to work.
I changed the gradle compile statement from 
`compile 'com.koushikdutta.async:androidasync:2.+'` 
as is mentioned in Readme of repository
to 
`compile 'com.koushikdutta.async:androidasync:2.1.6'`
and its working for now
