### ISSUE TITLE
FATAL EXCEPTION: AsyncServer

### ISSUE THREAD

**Issue by pradeepkotha** [koush/AndroidAsync#545]
FATAL EXCEPTION: AsyncServer
                                                                               
                                                                                  java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'void javax.net.ssl.SSLEngine.setUseClientMode(boolean)' on a null object reference
                                                                                      at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:852)
                                                                                      at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658)
                                                                                      at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
                                                                                      at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600)
                                                                                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void javax.net.ssl.SSLEngine.setUseClientMode(boolean)' on a null object reference
                                                                                      at com.koushikdutta.async.AsyncSSLSocketWrapper.<init>(AsyncSSLSocketWrapper.java:136)
                                                                                      at com.koushikdutta.async.AsyncSSLSocketWrapper.handshake(AsyncSSLSocketWrapper.java:101)
                                                                                      at com.koushikdutta.async.http.AsyncSSLSocketMiddleware.tryHandshake(AsyncSSLSocketMiddleware.java:89)
                                                                                      at com.koushikdutta.async.http.AsyncSSLSocketMiddleware$2.onConnectCompleted(AsyncSSLSocketMiddleware.java:106)
                                                                                      at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:849)
                                                                                      at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658) 
                                                                                      at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44) 
                                                                                      at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600)

**Comment by pradeepkotha** [comment]
@koush  Can you please help me out

**Comment by pradeepkotha** [comment]
@koush I am getting this exception and app is crashing so i could not move forward.
