### ISSUE TITLE
您好 我是新手  我目前遇到问题 

### ISSUE THREAD

**Issue by 18667366881** [koush/AndroidAsync#548]
07-10 13:48:50.200 29386-29412/com.example.administrator.socketapplication W/System.err: java.lang.NumberFormatException: Invalid int: "0,"message""
07-10 13:48:50.200 29386-29412/com.example.administrator.socketapplication W/System.err:     at java.lang.Integer.invalidInt(Integer.java:137)
07-10 13:48:50.200 29386-29412/com.example.administrator.socketapplication W/System.err:     at java.lang.Integer.parse(Integer.java:374)
07-10 13:48:50.200 29386-29412/com.example.administrator.socketapplication W/System.err:     at java.lang.Integer.parseInt(Integer.java:365)
07-10 13:48:50.200 29386-29412/com.example.administrator.socketapplication W/System.err:     at java.lang.Integer.parseInt(Integer.java:331)
07-10 13:48:50.200 29386-29412/com.example.administrator.socketapplication W/System.err:     at com.koushikdutta.async.http.socketio.SocketIOConnection$2.transform(SocketIOConnection.java:119)
07-10 13:48:50.200 29386-29412/com.example.administrator.socketapplication W/System.err:     at com.koushikdutta.async.http.socketio.SocketIOConnection$2.transform(SocketIOConnection.java:113)
07-10 13:48:50.200 29386-29412/com.example.administrator.socketapplication W/System.err:     at com.koushikdutta.async.future.TransformFuture.onCompleted(TransformFuture.java:14)
07-10 13:48:50.200 29386-29412/com.example.administrator.socketapplication W/System.err:     at com.koushikdutta.async.future.SimpleFuture.handleCallbackUnlocked(SimpleFuture.java:107)
07-10 13:48:50.200 29386-29412/com.example.administrator.socketapplication W/System.err:     at com.koushikdutta.async.future.SimpleFuture.setComplete(SimpleFuture.java:141)
07-10 13:48:50.200 29386-29412/com.example.administrator.socketapplication W/System.err:     at com.koushikdutta.async.future.SimpleFuture.setComplete(SimpleFuture.java:128)
07-10 13:48:50.200 29386-29412/com.example.administrator.socketapplication W/System.err:     at com.koushikdutta.async.http.AsyncHttpClient.invokeWithAffinity(AsyncHttpClient.java:523)
07-10 13:48:50.200 29386-29412/com.example.administrator.socketapplication W/System.err:     at com.koushikdutta.async.http.AsyncHttpClient.access$800(AsyncHttpClient.java:51)
07-10 13:48:50.200 29386-29412/com.example.administrator.socketapplication W/System.err:     at com.koushikdutta.async.http.AsyncHttpClient$7.run(AsyncHttpClient.java:534)
07-10 13:48:50.200 29386-29412/com.example.administrator.socketapplication W/System.err:     at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:740)
07-10 13:48:50.200 29386-29412/com.example.administrator.socketapplication W/System.err:     at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:758)
07-10 13:48:50.200 29386-29412/com.example.administrator.socketapplication W/System.err:     at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658)
07-10 13:48:50.200 29386-29412/com.example.administrator.socketapplication W/System.err:     at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
07-10 13:48:50.200 29386-29412/com.example.administrator.socketapplication W/System.err:     at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600)

**Comment by 18667366881** [comment]
Here is the code

**Comment by 18667366881** [comment]
SocketIOClient.connect(AsyncHttpClient.getDefaultInstance(),"http://192.168.0.101:2020",new ConnectCallback() {
            @Override
            public void onConnectCompleted(Exception ex, SocketIOClient client) {
                if (ex != null) {
                    ex.printStackTrace();
                    System.out.println("链接错误"+ex);
                    return;
                }
                client.setStringCallback(new StringCallback() {
                    @Override
                    public void onString(String string, Acknowledge acknowledge) {
                        System.out.println(string);
                    }

                    @Override
                    public void onString(String string) {
                        System.out.println(string);
                    }
                });
                client.on("someEvent", new EventCallback() {
                    @Override
                    public void onEvent(JSONArray argument, Acknowledge acknowledge) {
                        System.out.println("args: " + argument.toString());
                    }
                });
                client.setJSONCallback(new JSONCallback() {
                    @Override
                    public void onJSON(JSONObject json, Acknowledge acknowledge) {
                        System.out.println("json: " + json.toString());
                    }
                    @Override
                    public void onJSON(JSONObject json) {
                        System.out.println("json: " + json.toString());
                    }
                });
            }
        });
