### ISSUE TITLE
SSL issues on sdk 26

### ISSUE THREAD

**Issue by monil1334** [koush/AndroidAsync#553]
Stuck in loop when parsing the response.

javax.net.ssl.SSLHandshakeException: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
    at com.android.org.conscrypt.OpenSSLEngineImpl.shutdownWithError(OpenSSLEngineImpl.java:1107)
    at com.android.org.conscrypt.OpenSSLEngineImpl.sslReadErrorResult(OpenSSLEngineImpl.java:1098)
    at com.android.org.conscrypt.OpenSSLEngineImpl.unwrap(OpenSSLEngineImpl.java:798)
    at com.android.org.conscrypt.OpenSSLEngineImpl.unwrap(OpenSSLEngineImpl.java:636)
    at com.android.org.conscrypt.OpenSSLEngineImpl.unwrap(OpenSSLEngineImpl.java:602)
    at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:194)
    at com.koushikdutta.async.Util.emitAllData(Util.java:23)
    at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
    at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:821)
    at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658)
    at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
    at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600)

**Comment by koush** [comment]
latest ion?

**Comment by koush** [comment]
Can you get me an android device and OS version? and whether you are using google play services?

**Comment by monil1334** [comment]
I was using android emulator that had the google play intel x86 system image for Android 8.0. I have some verification code for play services if they exist on the phone.

**Comment by koush** [comment]
Ahh ok. There's a bunch of known/critical conscrypt bugs in Android 8.0 itself. It looks like you're using the system conscrypt vs google play conscrypt, which is why it is failing. Let me take a look again.

**Comment by poovamraj** [comment]
I am facing the same issue

**Comment by poovamraj** [comment]
I just solved the issue by using SSLContext.getInstance("TLSv1.2");
following this stackoverflow post https://stackoverflow.com/questions/40987859/sslexception-in-android-7-but-not-6

**Comment by poovamraj** [comment]
I am facing the same issue

**Comment by koush** [comment]
can you give me a url i an test against? I was unable to repro this on the latest Pixel XL 26 emulator.

**Comment by monil1334** [comment]
I was testing for work environment and it would probably require credentials to get in. Let me see if i can have something for you so you can hit and see what is happening

**Comment by monil1334** [comment]
@koush did you change something in the library ? I am getting a different error now..its saying unable to parse TLS packet header.

javax.net.ssl.SSLException: Unable to parse TLS packet header
    at com.android.org.conscrypt.OpenSSLEngineImpl.unwrap(OpenSSLEngineImpl.java:707)
    at com.koushikdutta.async.Util.emitAllData(Util.java:23)
    at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
    at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:821)
    at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658)
    at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
    at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600)
    at com.android.org.conscrypt.OpenSSLEngineImpl.unwrap(OpenSSLEngineImpl.java:602)
    at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:194)

**Comment by koush** [comment]
https://github.com/koush/ion/issues/825

**Comment by daluu** [comment]
Has this since been fixed in official release of Android O and subsequent newer Android OS versions?
