### ISSUE TITLE
Why use AsyncDatagramSocket.openDatagram will cause bind exception?

### ISSUE THREAD

**Issue by BearnLee** [koush/AndroidAsync#584]
hello,
I have a question that when i call this method cause bind exception,code as below:

AsyncDatagramSocket   asyncDatagramSocket = AsyncServer.getDefault().openDatagram("host", true);

I only can use "host",When i change "host" to a new remote ip(192.168.x.x), it will cause bind exception,can you help me to find it out what is the problem?

**Comment by scsfwgy** [comment]
you can write the exception here.

**Comment by BearnLee** [comment]
Datagram error
                                                                                 java.net.BindException: bind failed: EADDRNOTAVAIL (Cannot assign requested address)
                                                                                     at libcore.io.IoBridge.bind(IoBridge.java:89)
                                                                                     at java.net.PlainDatagramSocketImpl.bind(PlainDatagramSocketImpl.java:68)
                                                                                     at java.net.DatagramSocket.bind(DatagramSocket.java:457)
                                                                                     at java.nio.DatagramChannelImpl$DatagramSocketAdapter.bind(DatagramChannelImpl.java:536)
                                                                                     at com.koushikdutta.async.AsyncServer$11.run(AsyncServer.java:492)
                                                                                     at com.koushikdutta.async.AsyncServer$3.run(AsyncServer.java:194)
                                                                                     at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:709)
                                                                                     at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:726)
                                                                                     at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:627)
                                                                                     at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
                                                                                     at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:569)



this is the exception.

**Comment by scsfwgy** [comment]
![image](https://user-images.githubusercontent.com/16045179/34863525-d9c427b8-f7aa-11e7-849e-ae05ece2eb31.png)

your host is not available。or try use:http://your ip?

**Comment by BearnLee** [comment]
Thanks for your advise,
I have a try what you said,but the result is the same.
Here is the difference "localhost" and "192.168.xx.xx" 
![tim 20180112152417](https://user-images.githubusercontent.com/15085401/34864571-d9e1298a-f7af-11e7-8d0f-40998acc210c.png)
![tim 20180112152547](https://user-images.githubusercontent.com/15085401/34864585-eb68df72-f7af-11e7-83a5-666346b8f155.png)
But I still can't find that why this method cause the exception.
