### ISSUE TITLE
javax.net.ssl.SSLException: Unable to create application data

### ISSUE THREAD

**Issue by BapaiahMandava** [koush/AndroidAsync#601]
When application on ideal for long time and user performs any action the app crashes with below log.

Caused by javax.net.ssl.SSLException: Unable to create application data
       at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_new(:com.google.android.gms@12521023@12.5.21 (040408-189987672))
       at com.google.android.gms.org.conscrypt.SslWrapper.newInstance(:com.google.android.gms@12521023@12.5.21 (040408-189987672))
       at com.google.android.gms.org.conscrypt.ConscryptEngine.newSsl(:com.google.android.gms@12521023@12.5.21 (040408-189987672))
       at com.google.android.gms.org.conscrypt.ConscryptEngine.<init>(:com.google.android.gms@12521023@12.5.21 (040408-189987672):12)
       at com.google.android.gms.org.conscrypt.OpenSSLContextImpl.engineCreateSSLEngine(:com.google.android.gms@12521023@12.5.21 (040408-189987672):4)
       at javax.net.ssl.SSLContext.createSSLEngine(SSLContext.java:395)
       at com.koushikdutta.async.http.SSLEngineSNIConfigurator.createEngine(SSLEngineSNIConfigurator.java:68)
       at com.koushikdutta.async.http.AsyncSSLSocketMiddleware.createConfiguredSSLEngine(AsyncSSLSocketMiddleware.java:67)
       at com.koushikdutta.async.http.AsyncSSLSocketMiddleware.tryHandshake(AsyncSSLSocketMiddleware.java:90)
       at com.koushikdutta.async.http.AsyncSSLSocketMiddleware$2.onConnectCompleted(AsyncSSLSocketMiddleware.java:106)
       at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:849)
       at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658)
       at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
       at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600)

**Comment by ChinaSean** [comment]
+1 what to do?

**Comment by bytuncay** [comment]
+1 what to do ?

**Comment by svenjung** [comment]
+1 what to do ?

**Comment by 3c133ps3d** [comment]
+100500 how can we avoid this?

**Comment by HariharanEswaran** [comment]
How to fix this?
