### ISSUE TITLE
BufferedDataSink.write still hangs

### ISSUE THREAD

**Issue by weiqj** [koush/AndroidAsync#604]
This is the stack trace:

        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1022)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1328)
        at java.util.concurrent.Semaphore.acquire(Semaphore.java:318)
        at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:216)
        at com.koushikdutta.async.BufferedDataSink.write(BufferedDataSink.java:64)
        at com.koushikdutta.async.BufferedDataSink.write(BufferedDataSink.java:59)

**Comment by minichma** [comment]
Could be related to #612
