### ISSUE TITLE
Unable to connect to websocket in Android 8.1

### ISSUE THREAD

**Issue by rakeshdkaatkar** [koush/AndroidAsync#609]

**Comment by rakeshdkaatkar** [comment]
07-18 13:23:25.683 W/System.err(12167): javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
07-18 13:23:25.684 W/System.err(12167): at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:285)
07-18 13:23:25.684 W/System.err(12167): at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1091)
07-18 13:23:25.684 W/System.err(12167): at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1046)
07-18 13:23:25.684 W/System.err(12167): at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:805)
07-18 13:23:25.684 W/System.err(12167): at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:678)
07-18 13:23:25.684 W/System.err(12167): at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:644)
07-18 13:23:25.685 W/System.err(12167): at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:191)
07-18 13:23:25.685 W/System.err(12167): at com.koushikdutta.async.Util.emitAllData(Util.java:23)
07-18 13:23:25.685 W/System.err(12167): at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146)
07-18 13:23:25.685 W/System.err(12167): at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
07-18 13:23:25.685 W/System.err(12167): at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
07-18 13:23:25.685 W/System.err(12167): at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
07-18 13:23:25.685 W/System.err(12167): at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
07-18 13:23:25.686 W/System.err(12167): Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
Thread started:  #1407-18 13:23:25.686 W/System.err(12167):   at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:661)

**Comment by Mahan3340** [comment]
@amrgowda & @rakeshdkaatkar I had the same issue till i solved it this way check if out to see if its working for you 
https://stackoverflow.com/questions/50998503/socket-always-time-out-with-android-libraries
