### ISSUE TITLE
Repeat crashes

### ISSUE THREAD

**Issue by stom79** [koush/AndroidAsync#657]
I often get this crash recently, is it something on my end?

```log
07-29 17:44:04.221 E/AndroidRuntime(28479): java.lang.AssertionError: double connect callback 
07-29 17:44:04.221 E/AndroidRuntime(28479): at com.koushikdutta.async.http.AsyncHttpClient$3.onConnectCompleted(AsyncHttpClient.java:262) 
07-29 17:44:04.221 E/AndroidRuntime(28479): at com.koushikdutta.async.http.AsyncSSLSocketMiddleware$1.onHandshakeCompleted(AsyncSSLSocketMiddleware.java:83) 
07-29 17:44:04.221 E/AndroidRuntime(28479): at com.koushikdutta.async.AsyncSSLSocketWrapper.handleHandshakeStatus(AsyncSSLSocketWrapper.java:331) 
07-29 17:44:04.221 E/AndroidRuntime(28479): at com.koushikdutta.async.AsyncSSLSocketWrapper.write(AsyncSSLSocketWrapper.java:401) 
07-29 17:44:04.221 E/AndroidRuntime(28479): at com.koushikdutta.async.AsyncSSLSocketWrapper.handleHandshakeStatus(AsyncSSLSocketWrapper.java:276) 
07-29 17:44:04.221 E/AndroidRuntime(28479): at com.koushikdutta.async.AsyncSSLSocketWrapper.access$000(AsyncSSLSocketWrapper.java:30) 
07-29 17:44:04.221 E/AndroidRuntime(28479): at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:213) 
07-29 17:44:04.221 E/AndroidRuntime(28479): at com.koushikdutta.async.Util.emitAllData(Util.java:23) 
07-29 17:44:04.221 E/AndroidRuntime(28479): at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152) 
07-29 17:44:04.221 E/AndroidRuntime(28479): at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:821) 
07-29 17:44:04.221 E/AndroidRuntime(28479): at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658) 
07-29 17:44:04.221 E/AndroidRuntime(28479): at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44) 
07-29 17:44:04.221 E/AndroidRuntime(28479): at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600) 
07-29 17:44:04.223 E/ACRA    (28479): java.lang.AssertionError: double connect callback 
07-29 17:44:04.223 E/ACRA    (28479): at com.koushikdutta.async.http.AsyncHttpClient$3.onConnectCompleted(AsyncHttpClient.java:262) 
07-29 17:44:04.223 E/ACRA    (28479): at com.koushikdutta.async.http.AsyncSSLSocketMiddleware$1.onHandshakeCompleted(AsyncSSLSocketMiddleware.java:83) 
07-29 17:44:04.223 E/ACRA    (28479): at com.koushikdutta.async.AsyncSSLSocketWrapper.handleHandshakeStatus(AsyncSSLSocketWrapper.java:331) 
07-29 17:44:04.223 E/ACRA    (28479): at com.koushikdutta.async.AsyncSSLSocketWrapper.write(AsyncSSLSocketWrapper.java:401) 
07-29 17:44:04.223 E/ACRA    (28479): at com.koushikdutta.async.AsyncSSLSocketWrapper.handleHandshakeStatus(AsyncSSLSocketWrapper.java:276) 
07-29 17:44:04.223 E/ACRA    (28479): at com.koushikdutta.async.AsyncSSLSocketWrapper.access$000(AsyncSSLSocketWrapper.java:30) 
07-29 17:44:04.223 E/ACRA    (28479): at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:213) 
07-29 17:44:04.223 E/ACRA    (28479): at com.koushikdutta.async.Util.emitAllData(Util.java:23) 
07-29 17:44:04.223 E/ACRA    (28479): at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152) 
07-29 17:44:04.223 E/ACRA    (28479): at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:821) 
07-29 17:44:04.223 E/ACRA    (28479): at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658) 
07-29 17:44:04.223 E/ACRA    (28479): at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44) 
07-29 17:44:04.223 E/ACRA    (28479): at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600) 
```

**Comment by attaullahpro** [comment]
same issue but no any support from such repository. have you any solution???

**Comment by bobbyirawan09** [comment]
I also faces the same issue, any solution so far? this crash occurred the most in our crash report, around 800++
