### ISSUE TITLE
FATAL EXCEPTION: AsyncServer Process: com.myappname.android, PID: 3452    java.lang.AssertionError 

### ISSUE THREAD

**Issue by amodkanthe** [koush/AndroidAsync#689]
App is crashing in the Debug mode for the gradle version 4.1.1 following is the exception log for it. Crash not observed in the release build

`2020-12-11 16:49:48.301 3452-4136/com.myappname.android E/AndroidRuntime: FATAL EXCEPTION: AsyncServer
    Process: com.myappname.android, PID: 3452
    java.lang.AssertionError
        at com.koushikdutta.async.AsyncSSLSocketWrapper.write(AsyncSSLSocketWrapper.java:492)
        at com.koushikdutta.async.AsyncSSLSocketWrapper.handleHandshakeStatus(AsyncSSLSocketWrapper.java:378)
        at com.koushikdutta.async.AsyncSSLSocketWrapper.handshake(AsyncSSLSocketWrapper.java:182)
        at com.koushikdutta.async.http.AsyncSSLSocketMiddleware.tryHandshake(AsyncSSLSocketMiddleware.java:89)
        at com.koushikdutta.async.http.AsyncSSLSocketMiddleware$2.onConnectCompleted(AsyncSSLSocketMiddleware.java:106)
        at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:896)
        at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:717)
        at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:46)
        at com.koushikdutta.async.AsyncServer$11.run(AsyncServer.java:671)`

**Comment by koush** [comment]
already fixed in the latest version.
