### ISSUE TITLE
FATAL EXCEPTION: AsyncServer Process: me.wwts.test, PID: 2196 java.lang.AssertionError

### ISSUE THREAD

**Issue by wwtssu** [koush/AndroidAsync#698]
App is crashing in the debug mode but release mode works
2021-05-13 11:19:58.599 2196-12720/me.wwts.test E/AndroidRuntime: FATAL EXCEPTION: AsyncServer
    Process: me.wwts.test, PID: 2196
    java.lang.AssertionError
        at com.koushikdutta.async.AsyncSSLSocketWrapper.write(AsyncSSLSocketWrapper.java:390)
        at com.koushikdutta.async.AsyncSSLSocketWrapper.handleHandshakeStatus(AsyncSSLSocketWrapper.java:276)
        at com.koushikdutta.async.AsyncSSLSocketWrapper.handshake(AsyncSSLSocketWrapper.java:114)
        at com.koushikdutta.async.http.AsyncSSLSocketMiddleware.tryHandshake(AsyncSSLSocketMiddleware.java:89)
        at com.koushikdutta.async.http.AsyncSSLSocketMiddleware$2.onConnectCompleted(AsyncSSLSocketMiddleware.java:106)
        at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:849)
        at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658)
        at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
        at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600)

**Comment by rayworks** [comment]
Got the same error (Ion 2.2.1, gradle : 6.7.1, AS: 4.2.1).
