### ISSUE TITLE
exception when connect to server

### ISSUE THREAD

**Issue by sajjadshahbazi** [koush/AndroidAsync#711]
when connect to web service thows this exception : 

'
 FATAL EXCEPTION: AsyncServer
                                                                                                    , PID: 3343
                                                                                                    java.lang.AssertionError
                                                                                                    	at com.koushikdutta.async.AsyncSSLSocketWrapper.write(AsyncSSLSocketWrapper.java:390)
                                                                                                    	at com.koushikdutta.async.AsyncSSLSocketWrapper.handleHandshakeStatus(AsyncSSLSocketWrapper.java:276)
                                                                                                    	at com.koushikdutta.async.AsyncSSLSocketWrapper.handshake(AsyncSSLSocketWrapper.java:114)
                                                                                                    	at com.koushikdutta.async.http.AsyncSSLSocketMiddleware.tryHandshake(AsyncSSLSocketMiddleware.java:89)
                                                                                                    	at com.koushikdutta.async.http.AsyncSSLSocketMiddleware$2.onConnectCompleted(AsyncSSLSocketMiddleware.java:106)
                                                                                                    	at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:849)
                                                                                                    	at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658)
                                                                                                    	at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
                                                                                                    	at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600)
'

**Comment by mu-is-too-short** [comment]
Just came across the same issue while trying to open a secure websocket. I'm guessing you switched to something else since this project appears to be abandoned.
